{
    'name': "wsem_cloud_sas",
    'version': '1.0',
    'category': 'API',
    'depends': ['base', 'contacts', 'sale'],
    'data': [],
    'installable': True,
    'application': False,
    'auto_install': False,
    'summary': "Short summary of the module's purpose",
    'description': "Long description of module's purpose",
    'author': "Semantic Web Software SL",
    'website': "https://wsemantic.com",
    'license': "AGPL-3",
}
